language: php
php:
  # - '5.6'
  - '7.1'
  # - nightly
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE gatherling DEFAULT CHARACTER SET latin1;'
  - cp config.php.travisci config.php
  - php admin/db-upgrade.php
  - php util/updateDefaultFormats.php
